# Generated by Django 6.0.2 on 2026-03-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
