# Generated by Django 6.0.2 on 2026-03-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_orderitem_pedido_remove_orderitem_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['orden']},
        ),
    ]
